name: Matthew Jackson
pygments: true
permalink: /notes/:categories/:title
pagination: 1
exclude: ['node_modules' , 'sass', 'Gruntfile.js', '*.ai', '*.icns', 'mjlogo.sketch', 'mdpi', 'logo.sketch', 'package.json', '.gitignore', ]
markdown: redcarpet
