# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Matthew Jackson
email: hello@matthew-jackson.com
description: > # this means to ignore newlines until "baseurl:"
  Matthew Jackson is a Front-end Developer and Designer based in Wales, UK
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://matthew-jackson.com" # the base hostname & protocol for your site
twitter_username: matthewbeta
github_username:  matthewbeta

# Build settings
markdown: kramdown
theme: minima
highlighter: true
permalink: /notes/:categories/:title
plugins_dir: 
  - jekyll-paginate
pagination: 5
paginate_path: "/notes/page:num"
include: ["_headers"]

# Crosspost Settings
jekyll-crosspost_to_medium:
  enabled: false
  # cache: .jekyll-crosspost_to_medium
  # status: public (default) | draft | unlisted
  # license: all-rights-reserved (default) | cc-40-by | cc-40-by-sa | cc-40-by-nd | cc-40-by-nc | cc-40-by-nc-nd | cc-40-by-nc-sa | cc-40-zero | public-domain
  # text: '<p><i>Your (optional) signoff for the post.</i></p>',
  # backdate: true (default) | false